### ISSUE TITLE
0 friends updated

### ISSUE THREAD

**Issue by wesleytian** [bhamodi/facebook-online-friend-tracker#7]
I have gotten the Facebook Online Friend Tracker to work, but it doesn't correctly update the friends list (number of friends). It continuously shows 0 friends instead of the correct amount.

<img width="672" alt="this one" src="https://cloud.githubusercontent.com/assets/14323620/18318833/2e47352a-74f1-11e6-9c84-bb3c870693fc.png">

**Comment by bhamodi** [comment]
@wesleyyt - when looking at the Chrome browser, is the chat bar minimized or not? Refer to the conversation in #5, and let me know if that fixes it.

**Comment by wesleytian** [comment]
@bhamodi Great, thank you. It has updated the number of friends correctly now.
