### ISSUE TITLE
Get 0 online users all time

### ISSUE THREAD

**Issue by marcelomao7** [bhamodi/facebook-online-friend-tracker#8]
Initializing Chrome WebDriver...
Logging into Facebook...

Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
Done! Detected 0 online friends.
Added: 2016/09/19 00:19:41 -> 0 to the spreadsheet.

Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
Done! Detected 0 online friends.
Added: 2016/09/19 00:22:43 -> 0 to the spreadsheet.

Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
Done! Detected 0 online friends.
Added: 2016/09/19 00:27:43 -> 0 to the spreadsheet.

Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)
Done! Detected 0 online friends.
Added: 2016/09/19 00:32:43 -> 0 to the spreadsheet.

Waiting for Facebook to update friends list... (This takes approximately 3 minutes.)

**Comment by bhamodi** [comment]
@marcelomao7 - have you seen the solution proposed in #7 and #5?
